name: CI processs for andre-devsecops

on:
  [push]

jobs:
#First Workflow, run hello world directly
  Running_application_directly_from_console:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile and run Hello World! directly from the console
        shell: bash
        run: |
             pip install --no-cache-dir -r python_application/requirements.txt
             python python_application/hello_world.py
      - name: Upload hello_world python file into artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload_hello_world_python_file
          path: python_application/hello_world.py
      - name: Upload Dockerfile file into artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload_dockerfile_file
          path: python_application/Dockerfile
#Second Workflow, run hello world from docker
  Running_application_from_docker:
    runs-on: ubuntu-latest
    needs: running_andre-devsecops_app_workflow
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Download hello world artifact
        uses: actions/download-artifact@v4
        with:
          name: upload_hello_world_python_file
      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v4
        with:
          name: upload_dockerfile_file
      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: iilness/andre-devsecops-python:latest
      - name: Run image scanner for image results using Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'iilness/andre-devsecops-python:latest'
      - name: Running Hello World! from docker
        uses: docker://iilness/andre-devsecops-python:latest
